- hosts: jenkins
  remote_user: ec2-user
  become: yes
  vars:
    ports: 9090  
  tasks:
  - name: Add repository
    yum_repository:
      name: jenkins
      description: EPEL YUM repo
      baseurl: http://pkg.jenkins.io/redhat-stable
      gpgkey: http://pkg.jenkins.io/redhat-stable/jenkins.io.key   
  - name: install the latest version of java & Jenkins
    yum:
      name: "{{item}}"
      state: present
    loop:
      - java
      - jenkins
  - name: Chaning jenkins port
    lineinfile:
      path: /etc/sysconfig/jenkins
      regexp: '^JENKINS_PORT='
    notify: restart jenkins  
  - name: start service jenkins, if not started
    service:
      name: jenkins
      state: started    line: JENKINS_PORT={{ports}}
  handlers:
  - name: restart jenkins
    service:
      name: jenkins
      state: restarted