- hosts: jenkins
  remote_user: ec2-user
  become: yes
  tasks:
  - name: Upgrade all packages
    yum:
      name: '*'
      state: latest
  - name: Installing java
    yum:
      name: java-1.8.0-openjdk
      state: present
  - name: Download tomcat
    get_url:
      url: http://apachemirror.wuchna.com/tomcat-9/v9.0.46/bin/apache-tomcat-9.0.46.
      dest: /opt
      mode: '777'
  - name: unzip tomcat
    unarchive:
      src: /opt/apache-tomcat-9.0.46.tar.gz
      dest: /opt   
      remote_src: yes 
  - name: start tomcat
    shell: nohub /opt/apache-tomcat-9.0.46/bin/startup.sh &
    mode: '777'
  - name: changing server.xml port no
    template:
      src: /home/ec2-user/server.xml.j2
      dest: /opt/apache-tomcat-9.0.46/conf/server.xml
      mode: '777'
  - name: stopping tomcat
    shell: nohub /opt/apache-tomcat-9.0.46/bin/shutdown.sh &
  - name: copy files
    copy:
      src: /home/ect-user/sample.war
      dest: /opt/apache-tomcat-9.0.46/webapps
      mode: '0777'  